name: ffx
description: "ffx is a brand new life cycle + state management tool in flutter. It is intended to solve the templating problem written by StatefulWidget, simplify the code, and improve work efficiency."
version: 0.0.1
homepage: https://github.com/aymtools/ffx/
issue_tracker: https://github.com/aymtools/ffx/issues
topics:
  - compose
  - function-widget
  - remember

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.0
  cancellable: ^2.0.0
  anlifecycle: ^2.0.1
  weak_collections: ^1.1.0
  an_lifecycle_cancellable: ^0.0.2


dev_dependencies:
  flutter_lints: ^3.0.0

flutter: